Variation:
  - source(".") 
  - $tgv_id: tsv("tgv_id")
  - $chr_hs38: tsv("GRCh38_chromosome")
  - $pos_hs38: tsv("GRCh38_position")
  - $ref: tsv("GRCh38_reference")
  - $alt: tsv("GRCh38_alternate")
  - $hgnc_id: tsv("hgnc_id")
  - $consequence: tsv("consequence")
  - $chr_mm39: tsv("GRCm39_chromosome")
  - $pos_mm39: tsv("GRCm39_position")
  - "http://identifiers.org/hco/$chr_hs38/GRCh38#$pos_hs38-$ref-$alt"
  - variables:
    - tgvid: $tgv_id
    - hgnc_id: $hgnc_id
    - most_severe_consequence: $consequence
    - mogplus_variant:
      - "http://identifiers.org/mco/$chr_mm39/GRCm39#$pos_mm39-$ref-$alt"
